// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtdkxlojjbiuzwlhmdms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0ZGt4bG9qamJpdXp3bGhtZG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjI4NDQsImV4cCI6MjA2MDEzODg0NH0.3V3T_hV5aE7j8NaANik9gFqiDrlYUxeUY5aAMDniIBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);