
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtdkxlojjbiuzwlhmdms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0ZGt4bG9qamJpdXp3bGhtZG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjI4NDQsImV4cCI6MjA2MDEzODg0NH0.3V3T_hV5aE7j8NaANik9gFqiDrlYUxeUY5aAMDniIBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize site_stats table if not exists
const initSiteStats = async () => {
  try {
    const { data, error } = await supabase
      .from('site_stats')
      .select('id')
      .eq('id', 1)
      .maybeSingle();
      
    if (error && error.code !== 'PGRST116') {
      console.error("Error checking site_stats:", error);
      return;
    }
    
    if (!data) {
      const { error: insertError } = await supabase
        .from('site_stats')
        .insert({ id: 1, visitor_count: 1000 });
        
      if (insertError) {
        console.error("Error initializing site_stats:", insertError);
      }
    }
  } catch (error) {
    console.error("Error initializing site stats:", error);
  }
};

// Call initSiteStats when the app starts
initSiteStats();
